"""media table

Revision ID: 1b7fbeeb04c3
Revises: 8bdd9c1f1b60
Create Date: 2026-06-02 12:19:45.718041

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b7fbeeb04c3"
down_revision: Union[str, Sequence[str], None] = "8bdd9c1f1b60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("pk", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("media_url", sa.TEXT(), nullable=False),
        sa.Column("media_comments", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_unique_constraint(None, "admins", ["telegram_pk"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admins", type_="unique")
    op.drop_table("media")
    # ### end Alembic commands ###
